export interface IUser {
    _id:string,
    firstName: string,
    lastName: string,
    image: string,
    username: string,
    password: string,
    role: string,
    logo: string,
    firmcompanyId: number,
    employeeId: number,
    grant_type:string,
    firmName: string,
    displayFormat: string,
    employeeName : string,
    nameFormat : string,  
}